### PR TITLE
Apply fix from https://github.com/hellysmile/fake-useragent/pull/110

### PR DESCRIPTION
**Pull request by michaelhball**

### CODE REVIEW

**Comment by melroy89** [comment]
@hellysmile is from Ukraine.. Maybe that gives you enough info. I will create a fork: https://github.com/danger89/fake-useragent

**Comment by Christoph1987** [comment]
The fork seems to be as inactive as this project

**Comment by melroy89** [comment]
> The fork seems to be as inactive as this project

No? Last pr merge was 9 days ago. I don't know what you talking about.

**Comment by melroy89** [comment]
Solved by: https://github.com/hellysmile/fake-useragent/pull/136

**Pull request closed without merging**
