### PR TITLE
Add Google Style docstrings to codebase

### LINKED ISSUE #355: Methods should have docstrings
I think methods and instance variables should be documented with docstrings. With this, we could even deploy some pretty docs for free with GitHub pages.

Would you be willing to look into a PR documenting the codebase? I prefer Google Styled docstrings, but I could also submit them in Numpy if you're so inclined.

Ruff has some tools to ensure docstrings remain up-to-date with method signatures, and to ensure their formatting is correct. We could enable those.

### PR DESCRIPTION
**Pull request by sebastian-correa**
# Summary
This PR adds Google Style docstrings to the whole codebase.

After this, I'd say we can revive a documentation page (built with sphinx or mkdocs and hosted in GitHub pages or ReadTheDocs) with API docs and a simple tutorial (like in the README).

# Note
This has been opened as a draft because it merges into #364, but I can't point this PR to that branch without the PR getting opened on my fork:S.

Fixes: https://github.com/fake-useragent/fake-useragent/issues/355

### CODE REVIEW

**Comment by melroy89** [comment]
You now have file conflict with your own PR 😆  https://github.com/fake-useragent/fake-useragent/commit/4c54e9ed1f42fbbef0aebc826900568c65d233fc

**Comment by sebastian-correa** [comment]
My bad. Not used to using `black`.

**Comment by melroy89** [comment]
ow just run `black .` it should it fix automatically.

**Comment by sebastian-correa** [comment]
Haha I do know how to run it. It's just that I don't have it set to run automatically in VSCode, so I forget to do so. I think it's fine now.

**Comment by melroy89** [comment]
ow sorry, then I misunderstood you 😆

**Review by melroy89 — APPROVED** [review]
LGTM. It's still a draft or? It seems good enough already.

If it's ready you can press "ready for review":
image

**Comment by sebastian-correa** [comment]
> LGTM. It's still a draft or? It seems good enough already.
> 
> If it's ready you can press "ready for review": image

My bad @melroy89! I've been in a bit of a rush these last couple days and haven't been able to focus on this. Thanks for noticing it, I've marked as ready to review.

**Comment by melroy89** [comment]
No worries and no rush! It was just a question. Anyhow, thanks for marking it ready for review. It's clear now.

**Pull request merged**
