### PR TITLE
Useragent list update

### PR DESCRIPTION
**Pull request by BoudewijnZwart**
Updated the list of user agents. Also added a feature to select a specific platform and a minimum browser version. Removed the usage statistic feature as the new list does not have this attribute.

### CODE REVIEW

**Comment by BoudewijnZwart** [comment]
After this PR I will look at a way to automatically update the user agent list. I think that would be a good addition to this package. The website where I got the user agent list I used in this PR provides an API to retrieve current user agents.

**Comment by melroy89** [comment]
> After this PR I will look at a way to automatically update the user agent list. I think that would be a good addition to this package. The website where I got the user agent list I used in this PR provides an API to retrieve current user agents.

Avoid doing this on the client side btw. Like this pip package did in the past. It's a hell. Due to proxy setting, or firewalls or rate limit issues. Done that, I'm not going that route anymore.

My advise would be to leverage github actions and once a in a while via actions cron (yes github actions can be triggered in a predefined interval), fetch the remote data and update the json file in the git repo. Then we will just create a new package version once in a while.

**Comment by melroy89** [comment]
> Updated the list of user agents. Also added a feature to select a specific platform and a minimum browser version. Removed the usage statistic feature as the new list does not have this attribute.

Thanks! I will review this today in more detail. 

Be aware users might use this statistic feature maybe be backwards compatible as possible. Like also just randomly return data. Otherwise people have a hard time again during migration for now.

**Comment by BoudewijnZwart** [comment]
> > Updated the list of user agents. Also added a feature to select a specific platform and a minimum browser version. Removed the usage statistic feature as the new list does not have this attribute.
> 
> Thanks! I will review this today in more detail.
> 
> Be aware users might use this statistic feature maybe be backwards compatible as possible. Like also just randomly return data 🙄. Otherwise people have a hard time again during migration for now.

Good point. I put the feature back in and I gave every useragent a percentage of a 100 (so they all match regardless of the percentage chosen).

**Comment by BoudewijnZwart** [comment]
> > After this PR I will look at a way to automatically update the user agent list. I think that would be a good addition to this package. The website where I got the user agent list I used in this PR provides an API to retrieve current user agents.
> 
> Avoid doing this on the client side btw. Like this pip package did in the past. It's a hell. Due to proxy setting, or firewalls or rate limit issues. Done that, I'm not going that route anymore.
> 
> My advise would be to leverage github actions and once a in a while via actions cron (yes github actions can be triggered in a predefined interval), fetch the remote data and update the json file in the git repo. Then we will just create a new package version once in a while.

Ah good to know! Alright, I will have a look at GitHub actions and get back to you. That way might also put less stress on the API , as the updates are then done in the GitHub and not everybody has to do it themselves.

**Comment by melroy89** [comment]
> That way might also put less stress on the API , as the updates are then done in the GitHub and not everybody has to do it themselves

Correct. And on users behind a firewall, VPN or anything. This way we can guarantee the data is locally present at all times.

**Comment by melroy89** [comment]
> Good point. I put the feature back in and I gave every useragent a percentage of a 100 (so they all match regardless of the percentage chosen).

Great!

**Comment by melroy89** [comment]
@BoudewijnZwart I let the CI/CD (GItHub Actions) ran. But there seems to be some issues with linting and alike. 

Please fix the linting errors. See also: https://github.com/fake-useragent/fake-useragent?tab=readme-ov-file#linting

Also validate the test-cases, see: https://github.com/fake-useragent/fake-useragent?tab=readme-ov-file#tests

**Comment by BoudewijnZwart** [comment]
> @BoudewijnZwart I let the CI/CD (GItHub Actions) ran. But there seems to be some issues with linting and alike.
> 
> Please fix the linting errors. See also: https://github.com/fake-useragent/fake-useragent?tab=readme-ov-file#linting
> 
> Also validate the test-cases, see: https://github.com/fake-useragent/fake-useragent?tab=readme-ov-file#tests

Yes I will do. At the moment there is one linting rule that is a little more complicated to satisfy. The `__init__`  method has 8 arguments `(self,browsers,os,min_version,min_percentage,platforms,fallback,safe_attrs)` which is not allowed by the linter: 
image

However, I think you do want to keep all those arguments in the `__init__` method right? So one way would be to update the maximum number of function arguments in the pyproject.toml file from 7 to 8. If you do not want to adjust the linting rules an alternative could be to take the "min_version" argument out of the `__init__` method and just add it to the `getBrowser()` method. However, I feel like it would make more sense to adjust the linting rule and keep the way that all the parameters are treated uniform. What do you think @melroy89 ?

**Comment by BoudewijnZwart** [comment]
I made one inline linter exception for the amount of function arguments for the `__init__` method for the `FakeUserAgent` class. I think that is acceptable right? All the tests seem to pass and ruff is also happy right now.

**Comment by melroy89** [comment]
> However, I think you do want to keep all those arguments in the `__init__` method right? So one way would be to update the maximum number of function arguments in the pyproject.toml file from 7 to 8. If you do not want to adjust the linting rules an alternative could be to take the "min_version" argument out of the `__init__` method and just add it to the `getBrowser()` method. However, I feel like it would make more sense to adjust the linting rule and keep the way that all the parameters are treated uniform. What do you think @melroy89 ?

I agree with `PLR0913` exception here. Thanks for fixing.

**Comment by melroy89** [comment]
@BoudewijnZwart  After testing (there were no unit tests), I notice the platform parameter is giving errors:

```
>>> ua = UserAgent(platforms='mobile')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: FakeUserAgent.__init__() got an unexpected keyword argument 'platforms'
```

**Comment by melroy89** [comment]
Ow I notice there were missing unit tests.

**Comment by melroy89** [comment]
I did add for now a simple bad weather test on the `platforms` variable. But of course the unit-tests can be extended further to avoid regression impact in the future: https://github.com/fake-useragent/fake-useragent/commit/d10c549a295051a772d7214ab11a1f8828d9315f

**Comment by melroy89** [comment]
Anyhow, I did some additional fixes, some spelling mistakes in the README (`compability -> compatibility`) and updated the packages. And now v1.5.0 is out! 🥳

**Pull request merged**
