### PR TITLE
Publish tests

### PR DESCRIPTION
**Pull request by polyzen**
To be able to run the tests prior to installation, as part of building a distro package.

### CODE REVIEW

**Comment by polyzen** [comment]
Something like this may also be needed:
https://github.com/pexpect/ptyprocess/pull/22/commits/1fa2011142a200563a9b8fbf303a622ab643cff8

**Comment by hellysmile** [comment]
Hey @polyzen , what is `graft`?

**Comment by hellysmile** [comment]
I've found https://www.reddit.com/r/Python/comments/40s8qw/simplify_your_manifestin_commands/

**Comment by polyzen** [comment]
https://docs.python.org/3.7/distutils/commandref.html#sdist-cmd

**Pull request merged**
