### PR TITLE
Remove mutable defaults and allow more generic types

### PR DESCRIPTION
**Pull request by sebastian-correa**
# Summary
Solve #353 and #354 by removing mutable defaults and allowing more generic types than just `list`s/`tuple`s/`set`s.

# Details
## Mutable defaults
Mutable defaults are a bad idea since they're evaluated at definition time and mutating a default value in 1 instance will mutate it in all of them.

This PR solves bad mutable defaults by allowing the user to pass (and defaulting to) `None`, which retains the old behavior.

## More generic types
The code already worked for any `Iterable`s, as we only iterated on the values. These changes reflect that reality by not forcing the user to pass `list`s, but allowing them to pass any iterables and storing them as `list`s internally (to not change the API).

## `str_types` deprecation
`str_types` is a legacy thing from when the library supported Python 2, where the `str_types` were `str` and `unicode`. This PR deprecates the variable in favour of checking against `str`. This is a minor internal tweak.

# Questions
I replaced the `AssertionError`s with more aptly (IMO) suited `TypeError`s and `ValueError`s. Do you think this constitute a breaking change? Given the errors were raised only upon instantiation for validation and that they were undocumented behaviour, I'd say these are not breaking.

# Notes
I'm totally open to any critique/requests, and even to not merging the PR if you think it's not a good idea. Just let me know!

### CODE REVIEW

**Comment by melroy89** [comment]
Thanks once again for the PR! I will look tomorrow into it.

**Review by melroy89 — APPROVED** [review]
LGTM. I will test it locally a bit version. EDIT: Looks good! 🥳 

Ps. Sorry I couldn't test it earlier. There was some kind of Chinese & Singapore DDoS attack happening. Hopefully not using fake-useragent python package.. 🤕

**Comment by melroy89** [comment]
Also this is no longer a problem indeed:
```
>>> ua3.browsers
['chrome', 'firefox', 'safari', 'edge']
>>> ua3.browsers.append("opera")
>>> ua3.browsers
['chrome', 'firefox', 'safari', 'edge', 'opera']
>>> ua2 = FakeUserAgent()
>>> ua2.browsers
['chrome', 'firefox', 'safari', 'edge']
```

**Comment by sebastian-correa** [comment]
> Ps. Sorry I couldn't test it earlier. There was some kind of Chinese & Singapore DDoS attack happening. Hopefully not using fake-useragent python package.. 🤕

Haha, let's hope not. Thanks for the merge!

**Pull request merged**
