### PR TITLE
fix get_browsers. w3-table-all --> ws-table-all

### PR DESCRIPTION
**Pull request by robertsmd**
settings.BROWSERS_STATS_PAGE html changed.

### CODE REVIEW

**Comment by robertsmd** [comment]
fixes #112

**Comment by robertsmd** [comment]
also fixes #113

**Review by ghost — APPROVED** [review]

**Comment by antibill51** [comment]
Why is it still not merged?

**Comment by aprilahijriyan** [comment]
This PR needs to be merged immediately. 🥲

**Comment by emaniacs** [comment]
same PR https://github.com/hellysmile/fake-useragent/pull/125

**Comment by baderdean** [comment]
Hello, why this pretty old PR is not being accepted/rejected if it fixes a current bug (present in the pypi packaged version)? Is this project abandoned?

**Comment by melroy89** [comment]
Fixed by: https://github.com/hellysmile/fake-useragent/pull/136

**Pull request closed without merging**
