### PR TITLE
GitHub Action to run tox to replace Travis CI

### PR DESCRIPTION
**Pull request by cclauss**
Test results: https://github.com/cclauss/fake-useragent/actions

Work to be done in `tox.ini`:
* `isort` must be uncommented and fixed.
* `--ignore=tests/test_fake.py --ignore=tests/test_utils.py` must be removed from `pytest`.

Travis CI is on vacation... https://travis-ci.org/github/hellysmile/fake-useragent/builds

### CODE REVIEW

**Comment by melroy89** [comment]
I will merge https://github.com/hellysmile/fake-useragent/pull/136 soon which contains GitHub actions as well, but has failing test-cases. Where you fixed it all! 👏🏽 

That being said, let's see if you still have improvements or changes to that PR.

**Comment by cclauss** [comment]
It is important to remove travis ci as a required set of tests (see below) unless someone is going to subscribe to travis as it is no longer free for open source projects.

**Comment by melroy89** [comment]
I agree Travis is no longer free. Remove `tests/test_fake.py` is not ideal, since this is the main test. Rather fixing it now in https://github.com/hellysmile/fake-useragent/pull/136..

**Comment by melroy89** [comment]
@hellysmile didn't gave me enough rights to the repo yet to remove Travis from the required set in github.

**Pull request closed without merging**
